src/Entity/Admin/Notes.php
<?php

namespace App\Entity\Admin;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Admin\NotesRepository")
 */
class Notes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Category", inversedBy="notes")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $season_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Admin\Image", mappedBy="notes")
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $pdf;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\University", inversedBy="notes")
     */
    private $university;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSeasonAt(): ?\DateTimeInterface
    {
        return $this->season_at;
    }

    public function setSeasonAt(?\DateTimeInterface $season_at): self
    {
        $this->season_at = $season_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setNotes($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getNotes() === $this) {
                $image->setNotes(null);
            }
        }

        return $this;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getPdf(): ?string
    {
        return $this->pdf;
    }

    public function setPdf(?string $pdf): self
    {
        $this->pdf = $pdf;

        return $this;
    }

    public function getUniversity(): ?University
    {
        return $this->university;
    }

    public function setUniversity(?University $university): self
    {
        $this->university = $university;

        return $this;
    }
}

src/Controller/Admin/NotesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Admin\Notes;
use App\Form\Admin\NotesType;
use App\Repository\Admin\NotesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/notes")
 */
class NotesController extends AbstractController
{
    /**
     * @Route("/", name="admin_notes_index", methods={"GET"})
     */
    public function index(NotesRepository $notesRepository): Response
    {
        $notes=$notesRepository->getAllNotes();

        return $this->render('admin/notes/index.html.twig', [
            'notes' => $notes,
        ]);
    }

    /**
     * @Route("/new", name="admin_notes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $note = new Notes();
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            /*************** Image Upload ***********************/
            $file = $form['image']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }


                $note->setImage($fileName);
            }
            /*************** Image Upload Finish ***********************/

            /*************** File Upload ***********************/
            $file = $form['pdf']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('pdf_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $note->setPdf($fileName);
            }
            /*************** File Upload Finish ***********************/

            $entityManager->persist($note);
            $entityManager->flush();

            return $this->redirectToRoute('admin_notes_index');
        }

        return $this->render('admin/notes/new.html.twig', [

            'note' => $note,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_notes_show", methods={"GET"})
     */
    public function show(Notes $note): Response
    {
        return $this->render('admin/notes/show.html.twig', [
            'note' => $note,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_notes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Notes $note): Response
    {
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /*************** Image Upload ***********************/
            $file = $form['image']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $note->setImage($fileName);
            }
            /*************** Image Upload Finish ***********************/


            /*************** File Upload ***********************/
            $file = $form['pdf']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('pdf_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $note->setPdf($fileName);
            }
            /*************** File Upload Finish ***********************/

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_notes_index');
        }

        return $this->render('admin/notes/edit.html.twig', [

            'note' => $note,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        return  md5(uniqid());

    }

    /**
     * @Route("/{id}", name="admin_notes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Notes $note): Response
    {
        if ($this->isCsrfTokenValid('delete'.$note->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($note);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_notes_index');
    }
}

src/Controller/NotesController.php
<?php

namespace App\Controller;

use App\Entity\Admin\Notes;
use App\Form\NotesType;
use App\Repository\Admin\NotesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/notes")
 */
class NotesController extends AbstractController
{
    /**
     * @Route("/", name="user_notes_index", methods={"GET"})
     */
    public function index(NotesRepository $notesRepository): Response
    {
        $user=$this->getUser();
        return $this->render('notes/index.html.twig', [
            'notes' => $notesRepository->findBy(['userid'=>$user->getId()]),
        ]);
    }

    /**
     * @Route("/new", name="user_notes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $note = new Notes();
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            /*************** Image Upload ***********************/
            $file = $form['image']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                    $note->setImage($fileName);
            }
            /*************** Image Upload Finish ***********************/

            /*************** File Upload ***********************/
            $file = $form['pdf']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('pdf_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $note->setPdf($fileName);
            }
            /*************** File Upload Finish ***********************/

            $user=$this->getUser();
            $note->setUserid($user->getId());
            $note->setStatus("New");


            $entityManager->persist($note);
            $entityManager->flush();

            return $this->redirectToRoute('user_notes_index');
        }

        return $this->render('notes/new.html.twig', [
            'note' => $note,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_notes_show", methods={"GET"})
     */
    public function show(Notes $note): Response
    {
        return $this->render('notes/show.html.twig', [
            'note' => $note,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_notes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Notes $note): Response
    {
        $form = $this->createForm(NotesType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            /*************** Image Upload ***********************/
            $file = $form['image']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }


                $note->setImage($fileName);
            }
            /*************** Image Upload Finish ***********************/

            /*************** File Upload ***********************/
            $file = $form['pdf']->getData();

            if ($file) {
                $fileName = $this->generateUniqueFileName().'.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('pdf_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    //
                }
                $note->setPdf($fileName);
            }
            /*************** File Upload Finish ***********************/



            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_notes_index');
        }

        return $this->render('notes/edit.html.twig', [
            'note' => $note,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        return  md5(uniqid());

    }



    /**
     * @Route("/{id}", name="user_notes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Notes $note): Response
    {
        if ($this->isCsrfTokenValid('delete'.$note->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($note);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_notes_index');
    }
}

templates/notes/_delete_form.html.twig
<form method="post" action="{{ path('user_notes_delete', {'id': note.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ note.id) }}">
    <button class="btn btn-rounded btn-danger">Delete</button>
</form>

templates/notes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-rounded btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/notes/edit.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Notes{% endblock %}

{% block body %}

    <section id="single-page-header">
        <div class="overlay">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-left">
                            <h2>My Notes</h2>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-right">
                            <ol class="breadcrumb">
                                <li><a href="/user">My Profile</a></li>
                                <li class="active">My Notes</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="blog-archive">
        <div class="container">
            <div class="row">
                <div class="col-md-15">
                    <div class="blog-archive-area">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <aside class="blog-side-bar">

                                    {% include('user/usermenu.html.twig') %}
                                </aside>
                            </div>
                            <div class="col-md-10">
                                <div class="blog-archive-left">
                                    <!-- Start blog news single -->
                                    <article class="blog-news-single">

                                        <div class="blog-news-title">
                                            <h2>Edit Your Notes</h2>
                                            <div class="blog-news-details blog-single-details">




                                                {{ include('notes/_form.html.twig', {'button_label': 'Update'}) }}

                                                <table>
                                                    <tr><a href="{{ path('user_notes_index') }}" class="btn btn-rounded btn-primary">Back To List</a></tr>
                                                    <tr> {{ include('notes/_delete_form.html.twig') }}</tr>
                                                </table>





                                            </div>
                                        </div>


                                    </article>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




{% endblock %}

templates/notes/new.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Notes{% endblock %}

{% block body %}




    <section id="single-page-header">
        <div class="overlay">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-left">
                            <h2>My Notes</h2>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-right">
                            <ol class="breadcrumb">
                                <li><a href="/user">My Profile</a></li>
                                <li class="active">My Notes</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="blog-archive">
        <div class="container">
            <div class="row">
                <div class="col-md-15">
                    <div class="blog-archive-area">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <aside class="blog-side-bar">

                                    {% include('user/usermenu.html.twig') %}
                                </aside>
                            </div>
                            <div class="col-md-10">
                                <div class="blog-archive-left">
                                    <!-- Start blog news single -->
                                    <article class="blog-news-single">

                                        <div class="blog-news-title">
                                            <h2>Your Notes</h2>
                                            <div class="blog-news-details blog-single-details">

                                                 {{ include('notes/_form.html.twig') }}

                                                <a href="{{ path('user_notes_index') }}" class="btn btn-rounded btn-primary">Back to List</a>




                                            </div>
                                        </div>


                                    </article>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




{% endblock %}

templates/notes/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Notes{% endblock %}

{% block body %}




    <section id="single-page-header">
        <div class="overlay">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-left">
                            <h2>My Notes</h2>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="single-page-header-right">
                            <ol class="breadcrumb">
                                <li><a href="/user">My Profile</a></li>
                                <li class="active">My Notes</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="blog-archive">
        <div class="container">
            <div class="row">
                <div class="col-md-15">
                    <div class="blog-archive-area">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <aside class="blog-side-bar">

                                    {% include('user/usermenu.html.twig') %}
                                </aside>
                            </div>
                            <div class="col-md-10">
                                <div class="blog-archive-left">
                                    <!-- Start blog news single -->
                                    <article class="blog-news-single">

                                        <div class="blog-news-title">
                                            <h2>Your Notes</h2>
                                            <div class="blog-news-details blog-single-details">




                                                <table class="table">
                                                    <tbody>
                                                    <tr>
                                                        <th>Id</th>
                                                        <td>{{ note.id }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>University</th>
                                                        <td>{{ note.university.name }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Title</th>
                                                        <td>{{ note.title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Keywords</th>
                                                        <td>{{ note.keywords }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Description</th>
                                                        <td>{{ note.description }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Pdf</th>
                                                        <td><a href="{{ asset ('uploads/pdf/' ~note.pdf)}}"> Burdan indirebilirsiniz</a></td>
                                                    </tr>
                                                    <tr>
                                                        <th>Image</th>
                                                        <td><img src="{{ asset ('uploads/images/' ~note.image) }}" height="100"></td>
                                                    </tr>
                                                    <tr>
                                                        <th>Status</th>
                                                        <td>{{ note.status }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Season_at</th>
                                                        <td>{{ note.seasonAt ? note.seasonAt|date('Y-m-d H:i:s') : '' }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Created_at</th>
                                                        <td>{{ note.createdAt ? note.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Updated_at</th>
                                                        <td>{{ note.updatedAt ? note.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                                    </tr>
                                                    </tbody>
                                                </table>

                                                <a href="{{ path('user_notes_index') }}"class="btn btn-rounded btn-primary">Back to List</a>

                                                <a href="{{ path('user_notes_edit', {'id': note.id}) }}"class="btn btn-rounded btn-success">Edit</a>

                                                {{ include('notes/_delete_form.html.twig') }}





                                            </div>
                                        </div>


                                    </article>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




{% endblock %}